language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
sudo: required
dist: xenial
services:
  - xvfb
cache:
  directories:
    - $GDALINST
    - ~/.cache/pip
env:
  global:
    - GDALINST=$HOME/gdalinstall
    - GDALBUILD=$HOME/gdalbuild
before_install:
  - travis_wait 30 ./misc/install_gdal.sh
  - export PATH=$GDALINST/gdal-2.4.0/bin:$PATH
  - export LD_LIBRARY_PATH=$GDALINST/gdal-2.4.0/lib:$LD_LIBRARY_PATH
install:
  - pip install --upgrade setuptools pip mock
  - pip install -r requirements.txt
  - python setup.py install
script:
  - python setup.py test
addons:
  apt:
    packages:
      - libgeos-dev
      - libproj-dev
      - python-numpy
      - python3-numpy
